techpack: sm6150: use atomic_set for setting cpumask bits
Fixes an upstrea error from commit 1bf99c86b35b11c6661e59c9ed3880eb9217099f
../techpack/audio/asoc/sm6150.c:5811:15: error: incompatible pointer types passing 'atomic_t *' to parameter of type 'struct cpumask *' [-Werror,-Wincompatible-pointer-types]
        cpumask_copy(&substream->latency_pm_qos_req.cpus_affine, &mask);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/cpumask.h:553:49: note: passing argument to parameter 'dstp' here
static inline void cpumask_copy(struct cpumask *dstp,
                                                ^

Change-Id: Ie4f4c8d31b29ce6bed9a14d49e9560d91d24e3c3
Signed-off-by: Panchajanya1999 <panchajanya@azure-dev.live>